swagger: '2.0'
info:
  title: BlueJeans onVideo REST API
  description: Video That Works Where You Do, from the world's leader in cloud video communication.
  version: 1.0.0
  contact:
    name: Brandon Fuller
    url: http://bluejeans.com/
    email: brandon@bluejeans.com
host: api.bluejeans.com
securityDefinitions:
  access_token:
    type: apiKey
    name: access_token
    in: query
security:
  - access_token: []
schemes:
  - https
produces:
  - application/json
paths:
  /oauth2/token?password:
    post:
      summary: Authentication via Password Grant Type
      description: An access token can be obtained by using a user’s username and password.
      tags:
        - Authentication
      consumes:
        - application/json
      parameters:
        - name: payload
          description: Credentials and stuff
          in: body
          required: true
          schema:
            required:
              - grant_type
              - username
              - password
            properties:
              grant_type:
                type: string
                default: password
                description: The type of access token you are requesting.
              username:
                type: string
                default: "brandon@localcounselcollective.com"
                description: Your user name that you use to login to our site.
              password:
                type: string
                description: Your user password that you use to login to our site.
                format: password
      responses:
        '200':
          description: The settings for the room
          schema:
            type: array
            items:
              $ref: '#/definitions/Grant'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /oauth2/token?meeting:
    post:
      summary: Authentication via Meeting Grant Type
      description: This is not a traditional OAuth grant type, but it behaves closely to the password grant type. This level of authentication allows for obtaining access to the meeting only. If a Moderator passcode is sent, moderator privileges are granted. If an Attendee access code is passed, the access token will have a limited scope of access that an attendee has within a meeting.
      tags:
        - Authentication
      consumes:
        - application/json
      parameters:
        - name: payload
          description: Credentials and stuff
          in: body
          required: true
          schema:
            required:
              - grant_type
              - meetingNumericId
              - meetingPasscode
            properties:
              grant_type:
                type: string
                default: meeting_passcode
                description: The type of access token you are requesting.
              meetingNumericId:
                type: string
                description: Meeting ID
              meetingPasscode:
                type: string
                description: Pin
      responses:
        '200':
          description: The settings for the room
          schema:
            type: array
            items:
              $ref: '#/definitions/Grant'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /oauth2/token?client:
    post:
      summary: Authentication via Client Grant Type
      description: This grant type is commonly used by an app. Client ID and Secret are provisioned within the BlueJeans Enterprise Administration console.
      tags:
        - Authentication
      consumes:
        - application/json
      parameters:
        - name: payload
          description: Credentials and stuff
          in: body
          required: true
          schema:
            required:
              - grant_type
              - client_id
              - client_secret
            properties:
              grant_type:
                type: string
                default: client_credentials
                description: The type of access token you are requesting.
              client_id:
                type: string
                description: Meeting ID
              client_secret:
                type: string
                description: Pin
      responses:
        '200':
          description: The settings for the room
          schema:
            type: array
            items:
              $ref: '#/definitions/Grant'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /v1/user/{user_id}:
    get:
      summary: Get User Account Details
      description: >
        This endpoint retrieves the basic account details for a given user.
      tags:
        - Users
      security:
        - access_token: []
      parameters:
        - name: user_id
          in: path
          description: ID of user to use
          required: true
          type: integer
          default: 52199
      responses:
        '200':
          description: The settings for the user
          schema:
            $ref: "#/definitions/User"
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    put:
      summary: Update User Account Details
      description: This endpoint allows updating a user’s basic account details.
      tags:
        - Users
      parameters:
        - name: user_id
          in: path
          description: ID of user to use
          required: true
          type: integer
          default: 52199
        - name: user
          in: body
          description: The user details that you wish to update.
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        '200':
          description: The settings for the user
          schema:
            $ref: "#/definitions/User"
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /v1/user/{user_id}/room:
    get:
      summary: UserRoom
      description: >
        This endpoint gets a user’s default meeting settings.
      tags:
        - Users
      security:
        - access_token: []
      parameters:
        - name: user_id
          in: path
          description: ID of user to use
          required: true
          type: integer
          default: 52199
      responses:
        '200':
          description: The settings for the room
          schema:
            $ref: '#/definitions/Room'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    put:
      summary: UserRoom
      description: >
        This endpoint gets a user’s default meeting settings.
      tags:
        - Users
      security:
        - access_token: []
      parameters:
        - name: user_id
          in: path
          description: ID of user to use
          required: true
          type: integer
          default: 52199
        - name: room
          in: body
          description: The user's room details that you wish to update.
          required: true
          schema:
            $ref: "#/definitions/Room"
      responses:
        '200':
          description: The settings for the room
          schema:
            $ref: '#/definitions/Room'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /v1/user/{user_id}/scheduled_meeting:
    get:
      summary: Meeting
      description: >
        This endpoint gets a user’s default meeting settings.
      tags:
        - Users
      security:
        - access_token: []
      parameters:
        - name: user_id
          in: path
          description: ID of user to use
          required: true
          type: integer
          default: 52199
      responses:
        '200':
          description: The settings for the room
          schema:
            type: array
            items:
              $ref: '#/definitions/Meeting'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      summary: Meeting
      description: Create a meeting.
      tags:
        - Meeting
      security:
        - access_token: []
      parameters:
        - name: user_id
          in: path
          description: The ID of the user who owns the meeting. Your ID can be found in the response when you authorize and get your access token under the grant.scope.user.
          required: true
          type: integer
          default: 52199
        - name: email
          in: query
          description: If set to true, sends invitation emails to all listed participants.
          type: boolean
        - name: meeting
          in: body
          description: The user's room details that you wish to update.
          required: true
          schema:
            $ref: "#/definitions/Meeting"
      responses:
        '200':
          description: The settings for the room
          schema:
            $ref: '#/definitions/Meeting'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /v1/user/{user_id}/scheduled_meeting/{meeting_id}:
    get:
      summary: Meeting
      description: >
        This endpoint gets a user’s default meeting settings.
      tags:
        - Meeting
      security:
        - access_token: []
      parameters:
        - name: user_id
          in: path
          description: The ID of the user who owns the meeting. Your ID can be found in the response when you authorize and get your access token under the grant.scope.user.
          required: true
          type: integer
          default: 52199
        - name: meeting_id
          in: path
          description: The ID of the meeting you want to view. This is an integer value. You can find this ID by doing a list of meetings and referencing the "id" property.
          required: true
          type: integer
          default: 12345
      responses:
        '200':
          description: The settings for the room
          schema:
            $ref: '#/definitions/Meeting'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    put:
      summary: Meeting
      description: Update a meeting.
      tags:
        - Meeting
      security:
        - access_token: []
      parameters:
        - name: user_id
          in: path
          description: The ID of the user who owns the meeting. Your ID can be found in the response when you authorize and get your access token under the grant.scope.user.
          required: true
          type: integer
          default: 52199
        - name: meeting_id
          in: path
          description: The ID of the meeting you want to view. This is an integer value. You can find this ID by doing a list of meetings and referencing the "id" property.
          required: true
          type: integer
          default: 12345
        - name: meeting
          in: body
          description: The user's room details that you wish to update.
          required: true
          schema:
            $ref: "#/definitions/Meeting"
      responses:
        '200':
          description: The settings for the room
          schema:
            $ref: '#/definitions/Meeting'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Grant:
    type: object
    properties:
      access_token:
        type: integer
        description: Unique identifier for room.
      expires_in:
        type: integer
        description: Timestamp
      scope:
        $ref: '#/definitions/Scope'
  Scope:
    type: object
    properties:
      user:
        type: integer
        description: your user id
      partitionName:
        type: string
        description: the server farm you are on
  User:
    type: object
    properties:
      id:
        type: integer
        description: Unique identifier for the user.
        readOnly: true
      username:
        type: string
      firstName:
        type: string
        description: User's first name
      middleName:
        type: string
        description: User's middle name
      lastName:
        type: string
        description: User's last name
      emailId:
        type: string
        description: User's email address
      company:
        type: string
        description: User's company name
      title:
        type: string
        description: User's title
      phone:
        type: string
        description: User's phone
      profilePicture:
        type: string
        description: Path to user's profile picture
      timezone:
        type: string
        description: User's timezone
      timeFormat:
        type: integer
        description: User's preference of 12 or 24 hour time display
      language:
        type: string
        description: User's language code
  Room:
    type: object
    properties:
      id:
        type: integer
        description: Unique identifier for room.
        readOnly: true
      numericId:
        type: string
        description: Unique identifier for room.
      name:
        type: string
        description: Name of the room.
      originPopId:
        type: integer
      isLargeMeeting:
        type: boolean
      showVideoAnimations:
        type: boolean
      backgroundImage:
        type: string
      isModeratorLess:
        type: boolean
      welcomeMessage:
        type: string
      disallowChat:
        type: boolean
      encryptionType:
        type: string
      showAllParticipantsInIcs:
        type: boolean
      participantPasscode:
        type: string
      publishMeeting:
        type: boolean
      moderatorLess:
        type: boolean
      videoBestFit:
        type: boolean
      muteParticipantsOnEntry:
        type: boolean
      enforceMeetingEncryption:
        type: boolean
      enforceMeetingEncryptionAllowPSTN:
        type: boolean
      idleTimeout:
        type: integer
      defaultLayout:
        type: string
      playAudioAlerts:
        type: boolean
      personalMeetingId:
        type: integer
      moderatorPasscode:
        type: string
  Meeting:
    type: object
    properties:
      id:
        type: integer
        description: Unique identifier for meeting.
        readOnly: true
      title:
        type: string
      description:
        type: string
      start:
        type: integer
      end:
        type: integer
      timezone:
        type: string
      numericMeetingId:
        type: string
      attendeePasscode:
        type: string
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
